spring.application.name=news-ingestor
news.guardian.base-url=https://content.guardianapis.com
news.guardian.page-size=20

news.hackernews.base-url=https://hacker-news.firebaseio.com/v0
news.hackernews.max-stories=20

news.guardian.api-key=${GUARDIAN_API_KEY:}

spring.http.clients.connect-timeout=5s
spring.http.clients.read-timeout=10s

spring.docker.compose.file=../compose.yaml