CREATE TABLE articles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(50)  NOT NULL,
    external_id  VARCHAR(500) NOT NULL,
    title        TEXT         NOT NULL,
    url          TEXT         NOT NULL,
    summary      TEXT,
    published_at TIMESTAMPTZ  NOT NULL,
    received_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_articles_source_external_id UNIQUE (source, external_id)
);

CREATE INDEX idx_articles_published_at ON articles (published_at DESC);